enum BookReferenceId {
  genesis(referenceId: "gen"),
  exodus(referenceId: "exod"),
  leviticus(referenceId: "lev"),
  numbers(referenceId: "num"),
  deuteronomy(referenceId: "deut"),
  joshua(referenceId: "josh"),
  judges(referenceId: "judg"),
  ruth(referenceId: "ruth"),
  firstSamuel(referenceId: "1sam"),
  secondSamuel(referenceId: "2sam"),
  firstKings(referenceId: "1kgs"),
  secondKings(referenceId: "2kgs"),
  firstChronicles(referenceId: "1chr"),
  secondChronicles(referenceId: "2chr"),
  ezra(referenceId: "ezra"),
  nehemiah(referenceId: "neh"),
  esther(referenceId: "esth"),
  job(referenceId: "job"),
  psalms(referenceId: "ps"),
  proverbs(referenceId: "prov"),
  ecclesiastes(referenceId: "eccl"),
  songOfSolomon(referenceId: "song"),
  isaiah(referenceId: "isa"),
  jeremiah(referenceId: "jer"),
  lamentations(referenceId: "lam"),
  ezekiel(referenceId: "ezek"),
  daniel(referenceId: "dan"),
  hosea(referenceId: "hos"),
  joel(referenceId: "joel"),
  amos(referenceId: "amos"),
  obadiah(referenceId: "obad"),
  jonah(referenceId: "jonah"),
  micah(referenceId: "mic"),
  nahum(referenceId: "nah"),
  habakkuk(referenceId: "hab"),
  zephaniah(referenceId: "zeph"),
  haggai(referenceId: "hag"),
  zechariah(referenceId: "zech"),
  malachi(referenceId: "mal"),
  matthew(referenceId: "matt"),
  mark(referenceId: "mark"),
  luke(referenceId: "luke"),
  john(referenceId: "john"),
  acts(referenceId: "acts"),
  Romans(referenceId: "rom"),
  firstCorinthians(referenceId: "1cor"),
  secondCorinthians(referenceId: "2cor"),
  galatians(referenceId: "gal"),
  ephesians(referenceId: "eph"),
  philippians(referenceId: "phil"),
  colossians(referenceId: "col"),
  firstThessalonians(referenceId: "1thess"),
  secondThessalonians(referenceId: "2thess"),
  firstTimothy(referenceId: "1tim"),
  secondTimothy(referenceId: "2tim"),
  titus(referenceId: "titus"),
  philemon(referenceId: "phlm"),
  hebrews(referenceId: "heb"),
  james(referenceId: "jas"),
  firstPeter(referenceId: "1pet"),
  secondPeter(referenceId: "2pet"),
  firstJohn(referenceId: "1john"),
  secondJohn(referenceId: "2john"),
  thirdJohn(referenceId: "3john"),
  jude(referenceId: "jude"),
  revelation(referenceId: "rev");

  const BookReferenceId({required this.referenceId});

  final String referenceId;

  static BookReferenceId fromString(String referenceIdString) {
    print("Ovde sam $referenceIdString");
    return BookReferenceId.values.firstWhere((referenceId) => referenceId.referenceId == referenceIdString);
  }
}