enum BookReferenceId {
  genesis(value: "gen"),
  exodus(value: "exod"),
  leviticus(value: "lev"),
  numbers(value: "num"),
  deuteronomy(value: "deut"),
  joshua(value: "josh"),
  judges(value: "judg"),
  ruth(value: "ruth"),
  firstSamuel(value: "1sam"),
  secondSamuel(value: "2sam"),
  firstKings(value: "1kgs"),
  secondKings(value: "2kgs"),
  firstChronicles(value: "1chr"),
  secondChronicles(value: "2chr"),
  ezra(value: "ezra"),
  nehemiah(value: "neh"),
  esther(value: "esth"),
  job(value: "job"),
  psalms(value: "ps"),
  proverbs(value: "prov"),
  ecclesiastes(value: "eccl"),
  songOfSolomon(value: "song"),
  isaiah(value: "isa"),
  jeremiah(value: "jer"),
  lamentations(value: "lam"),
  ezekiel(value: "ezek"),
  daniel(value: "dan"),
  hosea(value: "hos"),
  joel(value: "joel"),
  amos(value: "amos"),
  obadiah(value: "obad"),
  jonah(value: "jonah"),
  micah(value: "mic"),
  nahum(value: "nah"),
  habakkuk(value: "hab"),
  zephaniah(value: "zeph"),
  haggai(value: "hag"),
  zechariah(value: "zech"),
  malachi(value: "mal"),
  matthew(value: "matt"),
  mark(value: "mark"),
  luke(value: "luke"),
  john(value: "john"),
  acts(value: "acts"),
  Romans(value: "rom"),
  firstCorinthians(value: "1cor"),
  secondCorinthians(value: "2cor"),
  galatians(value: "gal"),
  ephesians(value: "eph"),
  philippians(value: "phil"),
  colossians(value: "col"),
  firstThessalonians(value: "1thess"),
  secondThessalonians(value: "2thess"),
  firstTimothy(value: "1tim"),
  secondTimothy(value: "2tim"),
  titus(value: "titus"),
  philemon(value: "phlm"),
  hebrews(value: "heb"),
  james(value: "jas"),
  firstPeter(value: "1pet"),
  secondPeter(value: "2pet"),
  firstJohn(value: "1john"),
  secondJohn(value: "2john"),
  thirdJohn(value: "3john"),
  jude(value: "jude"),
  revelation(value: "rev");

  const BookReferenceId({required this.value});

  final String value;

  static BookReferenceId fromString(String referenceIdString) {
    return BookReferenceId.values.firstWhere((referenceId) => referenceId.value == referenceIdString);
  }
}